name: CI

on:
  push:
    branches:
      - main

jobs:
  uno:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar Mensaje
        run: echo "¡Hola mundo!"
        
      - name: Crear Archivo
        run: |
          touch hola.txt
          ls -al  # Lista los archivos para verificar

      - name: Agregar Texto al Archivo
        run: |
          echo "Hola mundo" >> hola.txt
          ls -al  # Lista nuevamente los archivos para verificar el cambio

      - name: Leer Archivo
        run: cat hola.txt

  dos:
    runs-on: ubuntu-latest
    needs: uno  # Este job depende de que 'uno' termine primero
    steps:
      - name: Mostrar Contenido del Directorio
        run: ls -al